create schema if not exists private;
alter function public.is_content_manager() set schema private;
alter function public.is_admin() set schema private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to anon, authenticated;
revoke all on function private.is_content_manager() from public, anon, authenticated;
revoke all on function private.is_admin() from public, anon, authenticated;
grant execute on function private.is_content_manager() to anon, authenticated;
grant execute on function private.is_admin() to authenticated;
create index comments_author_idx on public.comments(author_id);
create index comments_parent_idx on public.comments(parent_id);
create index homepage_section_videos_video_idx on public.homepage_section_videos(video_id);
create index moderation_actions_comment_idx on public.moderation_actions(comment_id);
create index moderation_actions_moderator_idx on public.moderation_actions(moderator_id);
create index reactions_user_idx on public.reactions(user_id);
create index video_artists_artist_idx on public.video_artists(artist_id);
create index video_events_video_idx on public.video_events(video_id);
create index video_events_viewer_idx on public.video_events(viewer_id);
create index videos_created_by_idx on public.videos(created_by);
create index videos_updated_by_idx on public.videos(updated_by);
